# Generated by Django 5.2.4 on 2025-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_comment_options_alter_todo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/completed_images/'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='todo/thumbnails/default_thumbnail.jpg', null=True, upload_to='todo/thumbnails/'),
        ),
    ]
